name: RPM Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: RPM Packaging
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Package x86_64 RPMs
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: rockylinux:9
          shell: /bin/bash
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            cat /etc/redhat-release
            yum -y install 'dnf-command(config-manager)'
            yum -y config-manager --set-enabled crb
            yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
            yum -y install git rpm-build rpm-sign rsync make python3-rpm-macros python3-devel
            make
            mv *.rpm /artifacts

      - name: Package aarch64 RPMs
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: arm64v8/rockylinux:9.2
          shell: /bin/bash
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            cat /etc/redhat-release
            yum -y install 'dnf-command(config-manager)'
            yum -y config-manager --set-enabled crb
            yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
            yum -y install git rpm-build rpm-sign rsync make python3-rpm-macros python3-devel
            make
            mv *.rpm /artifacts

      - name: Clone Package Repository
        uses: actions/checkout@v3
        with:
          repository: rockit-astro/packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run:
          packages/sign-and-push-packages.sh artifacts/*.rpm

